spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: aahar
    password: Vipul@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

huggingface:
  api:
    token: "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"

server:
  port: 8080
